version: '3.8'

services:
  # NGINX Reverse Proxy with SSL
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: transcendence-nginx
    ports:
      - "443:443"
      - "8080:80"
    depends_on:
      - frontend
      - backend-auth
      - backend-blockchain
    networks:
      - transcendence-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: transcendence-frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - transcendence-network
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  # Backend Auth Service
  backend-auth:
    build:
      context: ./Backend/Auth
      dockerfile: Dockerfile
    container_name: transcendence-backend-auth
    volumes:
      - database-auth:/app/database
    networks:
      - transcendence-network
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  # Backend Blockchain Service
  backend-blockchain:
    build:
      context: ./Backend/Blockchain
      dockerfile: Dockerfile
    container_name: transcendence-backend-blockchain
    networks:
      - transcendence-network
    environment:
      - NODE_ENV=development
    restart: unless-stopped


networks:
  transcendence-network:
    driver: bridge

volumes:
  node_modules_frontend:
  database-auth: